# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=256)),
                ('fname', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(verbose_name='Datetime created')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
